name: hyrule_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies:
  args: ^2.3.2
  clippy: ^1.0.0
  http: ^0.13.5
  mime: ^1.0.4
  path: ^1.8.3
  smart_arg: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
